- tools/dhtchat.cpp
`tools/dhtchat.cpp` needs `random` to compile for me (LLVM/OS X) and I suspect would elsewhere as well.
> tools: fix dhtchat compile, include random

- tools/dhtchat.cpp
Tool bug fix: dhtchat, for signed messages, was truncating messages at single words rather than sending the entire line.
> bug fix: in DHTChat tool, signed message should emit entire line

- tools/dhtnode.cpp
- tools/tools_common.h
I had some issues building the library with cygwin under windows, turns out the toolchain does not have great support for the std::to_string(); method hence using a stringstream is a quick alternative to ensure it builds.
> Fix building with Cygwin.

- include/opendht/dht.h
- python/tools/benchmark.py
- src/dht.cpp
We have noticed that nodes could begin transferring values to other nodes that wouldn't appear in other nodes' search cache. So, the process could repeat itself indefinitely.
So, in order to prevent all of this, the nodes now limit themselves to send and receive values only if they think they should store it. Additionally, a major function of the data persistence feature had to be fixed (findClosestNodes).
> Data persistence: only store relevant values

- src/utils.cpp
This fixes #26. This is due to an incompatibility between c++11 and llvm. Since I cannot reproduce the bug easily, I'll let Travis do that for me...
> Fix #26: add duration cast

- cmake/FindMsgpack.cmake
This error appeared not long ago after some changes in the msgpack-c project:
```
CMake Error at /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
Could NOT find Msgpack (missing: MSGPACK_LIBRARY) (Required is at least
version "1.2")
Call Stack (most recent call first):
/usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
cmake/FindMsgpack.cmake:46 (find_package_handle_standard_args)
CMakeLists.txt:22 (find_package)
```
The error, and a fix provided by the neovim project, is explained [here](https://github.com/neovim/neovim/pull/4075).
> Update FindMsgpack.cmake fixing "not found" error

- include/opendht/utils.h
This pull request refere to #34. 
I change the ascii comparaison by the std::ctype::isprint() function, which one is more accurate to the problem.
> Change ascii value to std::isprint() function

- include/opendht/indexation/pht.h
- src/Makefile.am
- src/indexation/pht.cpp
I fixe the Makefile.am from src, cause we were missing the pht file in it.
Now we can create the makefile using autotools again.
( cmake was already update )
> Fix the autotool Makefile, missing pht include

- include/opendht/indexation/pht.h
Hi,
There is a little bug in the Prefix code.
If you try to get a prefix that is not a multiple of 8, you will get some extra bits. (In fact you will get X % 8 extra bit), even if they are not print they are here.
Here is an example that illustrate that problem, and confirm it
http://pastebin.com/92q0ie6u
For the simplicity of my test i've change the `auto n=size_ / 8` by auto n=2.
Here is the output before patch :
`./test`
`01010101110000000` 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`^ extra bit here`
Here is the output after recompile all things :
`./test`
`01010101100000000` 
Btw there is an extra bit on the ouput cause i don't change the bn var.
So here is this pull request.
> Prefix bug - A bit may remain in a prefix

- include/opendht/indexation/pht.h
Hi,
I was trying to make my cache working, and during my test i test the function commonBits.
According to this test : http://pastebin.com/6qBXp995
**Edit** : In my comment i invert the 2 size of the string.
`_p.size_ = 9` and `p.size_ = 16`
CommonBits should return only 9 as value ( since there is only 9 bits into _p which is a prefix of p).
But in this test it return 10.
It could be related to your bug @sim590. [ You told me about a [random ?] bug into pht]
> [Bug] Correction of function commonBits

- include/opendht/indexation/pht.h
Reverts savoirfairelinux/opendht#48
After rechecking, this change didn't make sense.
> Revert "[Bug] Correction of function commonBits"

- CMakeLists.txt
As #47 made it clear, it appears that when cmake runs on some platforms, it can't figure out the linking flags itself. This patch adds this.
> Specifying linking libraries in CMake

- configure.ac
- python/Makefile.am
As highlighted in #45, autotools files didn't provide a way for uninstalling opendht python module. So I've written a solution for this using `pip`.
@aberaud: since python naming convention differ from platform to platform, I've chosen to check for the binary `pip3` for explicitely specifying the python version and since our python module is written in Python3. Tell me if this way is okay with you.
> [autotools] pip to uninstall python files

- include/opendht/dht.h
- src/dht.cpp
This path deletes copy-constructor and copy-assignement and
default defines move-contructor and move-assignement methods.
Also uses emplace_back than push_back on dht::store vector
to have a better efficiency.
Signed-off-by: Guillaume Roguez <guillaume.roguez@savoirfairelinux.com>
> dht: ensure to not copy Storage instances

- CMakeLists.txt
- include/opendht.h
- include/opendht/log.h
- python/opendht_cpp.pxd
- python/tools/benchmark.py
- src/Makefile.am
- tools/dhtnode.cpp
@aberaud, if you can merge this as it is pretty straightforward.
I want to specify that I've had to split `tools_common.h` for linking successfully with the cython generated shared object. Otherwise, some code that wouldn't be relevant to link with, like readline, would fail to link if not compiled with `-lreadline`. But cython module just doesn't need that, hence the split.
> Enabling dht log in the benchmark

- src/dht.cpp
This case would raise segmentation fault on some Mac OSX platforms when running with the compiled library (LLVM). However, there wasn't any runtime error when running a version compiled with gcc 5.3.0 on GNU/Linux.
> dht: fixes out of range container erase.

- include/opendht/dht.h
Some Android NDK uses gcc 4.9.0 and this one has a bug
that prevent to use "default" keyword to assign defaulted
methods (like move-constructor).
This issue has been solved in 4.9.2.
This patch permits gcc 4.9.0 support by implementing
by hand previously defaulted methods for gcc < 4.9.2 (limited to 4.9.x)
> fix support of gcc 4.9

- tools/dhtscanner.cpp
This is necessary for dual-stacked peers.
> dhtscanner: Report both IPv4 and IPv6 for the same ID

- src/indexation/pht.cpp
This is a change around the code doing the _inexact match lookup_. The algorithm should check the number of common bits between the target prefix and candidate prefix found in the leaves. However, by error, the code was comparing the target prefix with the wrong data: the indexed hash rather than the prefix key for that index entry.
@kaldoran, @aberaud: It's been a while since I worked on this part of the code. Can you review this?
> pht: fix invalid comparison, inexact match lookup

- doc/dhtnode.1
- tools/dhtnode.cpp
- tools/tools_common.h
I have fixed a `dhtnode`'s optional argument parsing problem and added a manpage.
> [dhtnode] user experience

- include/opendht/callbacks.h
- include/opendht/default_types.h
- include/opendht/dht.h
- include/opendht/dhtrunner.h
- include/opendht/network_engine.h
- include/opendht/securedht.h
- include/opendht/utils.h
- include/opendht/value.h
- src/dht.cpp
- src/dhtrunner.cpp
- src/network_engine.cpp
- src/securedht.cpp
- src/utils.cpp
- src/value.cpp
- tools/dhtnode.cpp
Since #70 had been merged, but then also secretely reverted, I'm referring to this PR. This is essentially containing the same code, but also addressing the matter discuessed in this [comment](https://github.com/savoirfairelinux/opendht/pull/70#issuecomment-222507513) properly.
This PR now includes:
- `DhtRunner::query` API method;
- `QueryCallback` callback used in `DhtRunner::query` signature;
- Proper `Query::Query(std::string)` initialization with both `Select` and `Where` functionnal structures;
- `dhtnode` is updated accordingly and introduces the command `q` which will let you start a `query`;
The following should be added:
I'm not sure if I'm missing something from the lists above. @aberaud: feel free to comment.
> [DHT] Queries: remote values filtering

- include/opendht/indexation/pht.h
- python/opendht.pyx
- python/opendht_cpp.pxd
- python/tools/dht/tests.py
- src/indexation/pht.cpp
- tools/dhtnode.cpp
- tools/tools_common.h
This PR enhances the `Pht` API:
- A `Key` is now `std::map<std::string, Blob>` rather than `std::map<std::string, Prefix>`.
- The `Pht` now depends on a key specification
using KeySpec = std::map<std::string, size_t>
This key specification sets the order, the number and the length of the fields in the key.
Other minor changes:
- `dhtnode` will handle the key spec by setting the keyspec for the pht with the first key entered by the user;
- the benchmark has been updated accordingly.
> [PHT] Key consistency

- src/dht.cpp
When querying from local storage with SELECT f, a FieldValueIndex with empty
fields was returned without considering the SELECT statement requiring only a
field "f".
> dht: return consistent query from local storage

- include/opendht/dht.h
- src/dht.cpp
Since the elements inside are going to be moved constantly during the life of the node, this design is better. Also, it works around a crash when the store is resized (elements inside moved) at some point (always happenned the 3rd time) for some reason. This bug was known when compiled with LLVM >7.3.0 (>clang-703.0.31).
> dht: make main store a vector<unique_ptr<Storage>>

- configure.ac
- src/Makefile.am
Addressing #75, this patch brings consistent versionning between Autotools and CMake.
> autotools: versionning consistent with CMake

- src/dht.cpp
This is addressing the issue #102.
> dht: fix sendListen loop bug

- include/opendht/dht.h
- src/dht.cpp
The number of currently requested nodes, formerly named currentGetRequests, was renamed since it was not accurately describing the behavior. The number we are counting is not the number of 'get' requests, but rather the number of nodes being requested simultaneously.
> dht: more accurate name for requested nodes count

- src/dht.cpp
When the put is performed just after a get, then the get will not include the value which was in the put.
This bug was found when using the new complete node splitting algorithm (after some hour of searching ).
> dht: Fix, get does not include the put value if its performed just after it.

- src/dht.cpp
After merging queries in master, there are two things that I didn't get right:
- When a 'get' request associated with a certain 'query' has been sent, we don't want to send it again, i.e. we don't care if it's pending or not as soon as it has been sent.
- Search::isDone doesn't need to compute with a time reference. It simply has to check its search nodes requests status.
> [dht] rework get timings after queries in master

- include/opendht/dht.h
- include/opendht/network_engine.h
- include/opendht/node_cache.h
- src/dht.cpp
- src/network_engine.cpp
- src/node_cache.cpp
Since `Dht::bootstrapSearch` was rewritten to use the node cache #101, it made it clear that `Search::refill` should be rewritten as such. However, then `Dht::bootstrapSearch` becomes irrelevant.
An enhancement to `Search::refill` (now `Dht::refill(Search&)`) is that it will let `Search::insertNode` review its whole list of nodes and then let it insert nodes up to `SEARCH_NODES` nodes. The previous method would not garantee this behavior since, most of the times, it would pass less than `SEARCH_NODES` nodes to insertNode.
> dht: unify bootstrapSearch and refill method using node cache

- src/dht.cpp
This fixes some issues 97b573c did introduce. For instance, some nodes would not expire properly and some of the timings computation were not right.
> dht: value pagination fix

- include/opendht/indexation/pht.h
- src/Makefile.am
- src/indexation/pht.cpp
- tools/dhtnode.cpp
This PR is the first step of the multidimensional key support for issue #44.
The second step is to include multidimensional with some unknown value or bit into the multidimensional key to insert on the PHT.
For example on the DhtNode : 
il Profile name:,surname:rey* could look up for a profil with unknown name and a surname that start with 'rey'. [This feature is ready to implement in this code, then next step is to change Pht::lookupStep.
> Pht: First step for multidimensional key

- src/indexation/pht.cpp
I add a filter that filter duplicated value : 
Here is a pastebin of what append with the modification 
http://pastebin.com/ZGL1MPew
First i insert 11 same value, then the lookup and there is only one value found (but 11 in storage)
Then i re-add 10 values (we are now above the maximum value in a node that should create a splitting).
Line 56 show that it does not since all values are the same (it also show only one of the 21 values in the storage table)
Finally : 
Line 68 to 72 show that there is 42 values in the storage (21 Canary + 21 values). 
This will be the new behaviour.
> pht : Filter of duplicate values

- src/dht.cpp
- src/network_engine.cpp
Prior to this patch and since the queries, `SearchNode::getStatus` would accumulate entries that would not be deleted when `find_node` operation would complete. Therefor, this was memory leak and also creating inconsistency in `canGet` timings.
> [dht] cover bad cases in SearchNode::canGet

- src/dht.cpp
Since pagination, a bug was making the listen feature unusable running in infinite loop. This also makes more sense than sending 'get' since the listen request is paired with a Query defining the values that have to be fetched.
> dht: before sending 'listen', send find_node

- include/opendht/dht.h
- include/opendht/value.h
- src/dht.cpp
- src/value.cpp
This is a rework of #7 using queries (#43) and the network engine atomic requests (#52). Now, the data persistence behavior will be to first probe for a value ID before sending it, therefor reducing the overall traffic substantially.
Here you can see a graph with the following properties:
- 1024 nodes
- 17.5 put operations per sec (1Ko)
- 8.5 node shutdowns per sec
- 8.5 node joins per sec
- *y axis*: Traffic of the whole network in Kb/s
- *x axis*: Time in seconds
<div style="text-align:center">
</div>
> dht: data persistence 2.0

- include/opendht/dht.h
- include/opendht/network_engine.h
- src/dht.cpp
When adding nodes from a `NodeExport` list in `DhtRunner`, the underlying `Dht` would not try to add the nodes to the routing table and/or searches. Since the entries in the node cache are not persistent (weak_ptr), the node would not stand a chance.
> dht: Dht::insertNode has to really insert

- include/opendht/dht.h
- include/opendht/dhtrunner.h
- src/dht.cpp
- src/dhtrunner.cpp
- src/network_engine.cpp
Using a list of bootstrap nodes, we recover from network loss by pinging those nodes continuously until connected.
Changes since last iteration:
* bug fix in pingNode callback
* all calls to bootstrap(string, string) go through tryBootstrapCoutinuously, this makes bootstrap name resolution asynchronous (new feature !), and dhtnode will retry to connect even when started disconnected
* name resolution doesn't lock bootstrap_mtx, and other minor refactoring
> dhtrunner: recover from network changes

- include/opendht/dht.h
- src/dht.cpp
The number of bad nodes is limited in order to help determine presence of connectivity changes. This is intended to address #137.
According to the tables, 25 is a good average value for big networks. If the network is small, normal search expiration process will handle the situation.
I have made the choice of merging the events of an expired search and connectivity change event. I think this is clear that those two are strongly linked together if not actually the same case. @aberaud what do you think? Take a look at [this line](https://github.com/savoirfairelinux/opendht/pull/138/files#diff-96c057f80526cd0b3abd165dedb9f8cfR613)
> search: detect connectivity changes

- src/dht.cpp
> dht: appropriate time info in permanent put ops

- include/opendht/dht.h
Reannouncing margin going from 5 seconds to ~~30~~10 seconds.
In the case of a "permanent put", refreshing values need to be done sooner than 5 seconds before the expiration time of the value. It is common for a "put" operation to take up to 5 seconds when a search is not synced. A search can easily become unsynced after 10 minutes.
> dht: make reannounce margin bigger, safer

- include/opendht/dht.h
- include/opendht/network_engine.h
- include/opendht/node.h
- include/opendht/request.h
- net.h
- src/dht.cpp
- src/network_engine.cpp
- src/node.cpp
Since the initial implementation of listen operation, multiple listen requests from a single node on a same hash was not possible without singular inconsistencies. The flaw was coming from the fact that nodes receiving listen request could not differentiate between listen refresh request and a new independent listen request.
This patch introduces the new `net::Socket` structure which in time will enable remote nodes to send update for a storage while differentiating between concurrent listen requests. A socket has a unique identifier which consists of a transaction id as defined in the OpenDHT protocol
> Listen consistency

- include/opendht/infohash.h
This const void* convertion method helps a lot with programs
that need to print the hash with a printf() like function.
> infohash: add helper to C string format conversion

- configure.ac
On some platforms, cython3 binary is called `cython` and on others, it's called `cython3`. The usual way to check if a python module is by doing the following:
```sh
echo 'import module' | $PYTHON
```
where `$PYTHON` is the Python binary you wish to check. Cython is a module.
CQFD
> autoconf: robustly check for cython3

- CMakeLists.txt
- src/Makefile.am
Seems like this file was forgotten in the buildtools' include arrays. Applications using opendht cannot build without that.
> buildtools: add def.h to include files

- include/opendht/infohash.h
Implementation of InfoHash::toCString() is broken
> remove InfoHash::toCString()

- src/dht.cpp
- src/securedht.cpp
Since Dht may be used as a separate and independant component and that it the property of a node ID to default to random is also wanted on this layer, I propose to move `node_id` config defaulting to random to the `Dht` class constructor.
> dht: randomize id in Dht layer

- include/opendht/request.h
- src/dht.cpp
Fixes a bug where some callbacks wouldn't be called when a dummy request was inserted to cancel some operation while not using the `net::Request::State::COMPLETED` flag as per 19c47ec.
> dht: standardize announce status check

- python/tools/benchmark.py
- python/tools/dht/tests.py
Two instructions were mutually misordered, hence the error message below:
```
Traceback (most recent call last):
File "benchmark.py", line 189, in <module>
bootstrap = wb.get_bootstrap()
File "benchmark.py", line 64, in get_bootstrap
bootstrap=[(self.remote_bootstrap, self.bs_port)] if self.remote_bootstrap else [])
File "/home/simon/prog/opendht/python/tools/dht/network.py", line 334, in __init__
ips = DhtNetwork.find_ip(iface)
File "/home/simon/prog/opendht/python/tools/dht/network.py", line 327, in find_ip
if_ip4 = netifaces.ifaddresses(iface)[netifaces.AF_INET][0]['addr']
ValueError: You must specify a valid interface name.
```
This error was partly reported in #59, more precisely in the first pastebin linked by @kaldoran.
> benchmark: fix invalid ifname error

- src/infohash.cpp
*h.end() only works on VS 2015 with
_SECURE_SCL=0
_ITERATOR_DEBUG_LEVEL=0
Also, if these flags are used when compiling opendht, it seems that any client program that wants to link against opendht also needs the same flags enabled, which is a terrible requirement to force on a client.
The proposed change makes the code a bit cleaner and doesn't require any preprocessor tricks.
> Avoid dereferencing an iterator to 'end()'

- MSVC/opendht.vcxproj
- src/crypto.cpp
I think the constexpr errors will be gone in vs2017's compiler
> remove vs2015 based constexpr error, update vs project files

- include/opendht/infohash.h
The operator declaration's signature did not match the definition and was not ignored buy the Microsoft compiler and causes missing symbol errors at link time.
> InfoHash: fix stream operator<< declaration

- CMakeLists.txt
- README.md
- configure.ac
- include/opendht/callbacks.h
- include/opendht/dht.h
- include/opendht/dht_interface.h
- include/opendht/dht_proxy_client.h
- include/opendht/dht_proxy_server.h
- include/opendht/dhtrunner.h
- include/opendht/securedht.h
- src/callbacks.cpp
- src/dht.cpp
- src/dht_proxy_client.cpp
- src/dht_proxy_server.cpp
- src/dhtrunner.cpp
- src/securedht.cpp
- tools/dhtchat.cpp
- tools/dhtnode.cpp
- tools/tools_common.h
cf #218, also fix #222
+ Add an abstract class to describe the Dht
+ Now, we can modify the Dht linked to a SecureDht. So we can choose
between the classic Dht and the Dht using a proxy.
+ Implement a basic client which can Get and Put values on the Dht using
the proxy.
+ Fix LISTEN endpoint for DhtProxyServer
+ Add listen/cancelListen for DhtProxyClient
+ Add connectivityChanged.
Note: Update `dhtnode` and `dhtchat` to have the ability to use the DhtProxyClient.
> proxy: implement DhtProxyClient

- include/opendht/dhtrunner.h
- src/dhtrunner.cpp
In the case of a broken pipe, the bound SockAddr structure refs are passed to startNetwork and are emptied before binding (and at the end of rcv_thread), which would mean that bindSocket will get a couple empty stuctures as parameters and fail.
> dhtrunner: pass SockAddrs by value to startNetwork

- tools/dhtnode.cpp
* dhtnode was generating twice an EC cert which rendered encryption
impossible since opendht lib is expecting an RSA public key to encrypt
the data for the destination.
* fix savoirfairelinux/opendht#238
> Generates RSA pairs for dhtnode instead of EC cert

- include/opendht/dht_proxy_client.h
- src/dht_proxy_client.cpp
Because getConnectivityStatus is called each time an operation fails,
when destroying the proxy_client, we stop all operations so it fails.
Fix #257
> proxy_client: avoid to call getConnectivityStatus() when destroying

- src/dht_proxy_server.cpp
> scheduler: avoid overflow causing 100% cpu usage

- include/opendht/dht_proxy_client.h
- include/opendht/dht_proxy_server.h
- src/dht_proxy_client.cpp
- src/dht_proxy_server.cpp
- tools/dhtnode.cpp
callback_id was used for token problems which are not present anymore.
Now token is sufficient and we can remove callback_id.
fix #246
> proxy: remove useless callback_id

- include/opendht/dht_proxy_server.h
- src/dht_proxy_server.cpp
Because we now have one listener for each client by hash, the token
is unnecessary here. Moreover, this check is invalid cause we use
a token equal to 0.
Also, clientId was not properly set. so every time someone launch a node
and do a listen on a hash, a new listener is generated and it results
by flooding the node of push notifications.
> proxy server, fix push listeners and avoid flooding nodes

- src/dht_proxy_client.cpp
If a device receives a push notification, we can assume that the
proxy is up and running (because it sends a push notification).
Indeed, if the proxy is declared as disconnected, no operatons will
be executed when a push notification is received. This state is logic
when not using push notifications (because the local node is down),
but here, the status depends more on the proxy than the local node.
> proxy: set status to CONNECTED when receiving a push notifications

- include/opendht/dht_proxy_server.h
- src/dht_proxy_server.cpp
dht_proxy_server: avoid mutex when getting /
The dht_proxy_server should be always up, so getNodesStats will
be pretty always up-to-date. We can add it into a job and avoid
to wait for this method to finish (and this method use an
internal lock) to have a quick answer about the status of the proxy.
Note: the update is forced during the initialization of the proxy
> dht_proxy_server: avoid mutex when getting /

- CMakeLists.txt
- configure.ac
- include/opendht/callbacks.h
- include/opendht/dht_proxy_server.h
- include/opendht/dhtrunner.h
- include/opendht/value.h
- src/Makefile.am
- src/callbacks.cpp
- src/dht_proxy_server.cpp
- src/dhtrunner.cpp
- src/value.cpp
Allow to retrieve all dht stats in a single API call using
the new method getNodeInfo() and the JSON-serializable
new structure NodeInfo.
> dhtrunner: add getNodeInfo()

- src/dhtrunner.cpp
Allows for faster recovery in case of CPU contention
> dhtrunner: decrease max packet handling delay to 500ms

- include/opendht/dht.h
- src/dht.cpp
- src/search.h
- src/storage.h
Fix 3 issues with permanent put:
* store: don't expire permanent values from local storage
* refresh: properly refresh "expiration" field in ValueStorage and reschedule value expiration
* search: reschedule permanent values announce for next expiration
> dht: permanent put improvements and fix

- include/opendht/dht_proxy_client.h
- src/dht_proxy_client.cpp
- src/dht_proxy_server.cpp
Since we authentificate listeners with the clientId and the hash and
we use only one listener by hash/clientId, we doesn't need to store
a token always equals to 0.
Note: also avoid to get multiple hashes for one push notification.
> proxy: remove useless token for push listeners

- src/Makefile.am
missing peer_discovery.o object in auto configure generated lib
> add peer_discovery.o object into auto configure lib

- include/opendht/dhtrunner.h
- include/opendht/peer_discovery.h
- src/dhtrunner.cpp
- src/peer_discovery.cpp
- tests/peerdiscoverytester.cpp
- tests/peerdiscoverytester.h
Remove the original functions, add the NodeInsertPack msgpack to support the generic transmission need for Jami account & opendht
> peerdiscovery: modify to add support for sending and receiving msgpack

- include/opendht/default_types.h
Give the ability to store more datas into an ImMessage
Issue: #345
> default_types: add metadatas map into ImMessage

- src/peer_discovery.cpp
fix the issue where bind() can be interrupted after calling publish() first
> peerdiscovery: bind socket problem fix

- src/dht_proxy_server.cpp
This fixed this after runtime trace from ASan:
```
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x7f7b5564e908 in operator new(unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:104
#1 0x7f7b54dbdeae in __gnu_cxx::new_allocator<unsigned long>::allocate(unsigned long, void const*) /usr/include/c++/9.1.0/ext/new_allocator.h:114
#2 0x7f7b54d9e3ed in std::allocator_traits<std::allocator<unsigned long> >::allocate(std::allocator<unsigned long>&, unsigned long) /usr/include/c++/9.1.0/bits/alloc_traits.h:444
#3 0x7f7b54d69dad in std::_Vector_base<unsigned long, std::allocator<unsigned long> >::_M_allocate(unsigned long) /usr/include/c++/9.1.0/bits/stl_vector.h:343
#4 0x7f7b5504e0b8 in void std::vector<unsigned long, std::allocator<unsigned long> …
```
> dhtproxy: fix indirect memleaks from rest router traits

- tools/proxy_node.html
Tested in chrome by allowing it: [chrome://flags/#allow-insecure-localhost]()
> tester: add https support to proxy_node

- include/opendht/http.h
- src/http.cpp
- tests/httptester.cpp
- tests/httptester.h
> A 100-continue expectation informs recipients that the client is about to send a (presumably large) message body in this request and wishes to receive a 100 (Continue) interim response if the request-line and header fields are not sufficient to cause an immediate success, redirect, or error response.
https://tools.ietf.org/html/rfc7231#section-5.1.1
Adds feature: ```request->set_header_field(restinio::http_field_t::expect, "100-continue");```
> http: handle expect 100-continue on post

- src/dhtrunner.cpp
This is a patch to get DHT logs when running `DHTLOGLEVEL=3 ./bin/dring -pcd`
> dhtrunner: fix context.logger handling

- src/http.cpp
the latter ensures that the request will be terminate even if the
http_parser on_message_complete callback is not called with an old
version of dhtproxy using restbed.
> http: end request on 0 body bytes

- src/dht_proxy_client.cpp
Moreover, when it's a subscribe, because the subscribe is direct
> dht_proxy_client: listener should not be stopped here

- MSVC/opendht.vcxproj
- include/opendht/sockaddr.h
- <stdexcept> is no longer included in <vector> as of vs 2019
> msvc: fix compilation with VS 2019 16.0

- src/dht_proxy_client.cpp
opstate is captured by value in callbacks. So reset(new OpState())
will only reset the new one and previously captured will be stopped
forever.
> proxy_client: reset correct opstate

- include/opendht/dht_proxy_client.h
- include/opendht/dht_proxy_server.h
- include/opendht/dhtrunner.h
- include/opendht/http.h
- src/dht_proxy_client.cpp
- src/dht_proxy_server.cpp
- src/dhtrunner.cpp
- src/http.cpp
- tests/dhtproxytester.cpp
- client test sample: [https_2waystls.cpp](https://github.com/binarytrails/various/blob/master/cpp/opendht/https_2waystls.cpp#L48
)
- server dhtproxy feature: #432
> http: add client identity

- src/http.cpp
This PR fixes the processing of ```Content-type: ocsp-response``` binary encoded body
> http: try to read full content-length after headers

- src/dht.cpp
Inside the if-statement, the log message will always print zero.
Confusingly, its the same message as the one in the loop above it.
Make the message distinct.
> Fix duplicated, non-functional log message.

- src/dht_proxy_client.cpp
- src/dhtrunner.cpp
When SecureDHT is initialized, a permanent put is done to announce the node
and then the push token is set. This means the the first permanent put will not
get expirations notification because it's considered as a non push device's put.
We should inject the push token as soon as possible.
> dhtproxyclient: setPushNotification before first permanent put

- include/opendht/peer_discovery.h
- src/dhtrunner.cpp
- src/peer_discovery.cpp
this makes peer discovery pub/sub on connectivity change, it aims to
make peer discovery more energy efficient.
also, stop echo'ing.
TODO:
in its current implementation however, peer_discovery operates in the
dark; it doesn't know routes available to it (v4 vs v6); nor does it
know of the state of the link(s) (UP vs. DOWN) and therefore it merely
tries to, on connectivity change, (re)pub/sub on previous ip version
routes.
IDEA:
open an interface to kernel so that peer discovery, and perhaps others,
can learn about the routes available to them.
> implement connectivity change in peer discovery

- opendht.pc.in
The -lpthread flag causes a build error when cross-compiling with Android NDK r21.
> opendht.pc: change -lpthread to -pthread

- include/opendht/dht.h
- include/opendht/network_engine.h
- src/dht.cpp
- src/listener.h
- src/net.h
- src/network_engine.cpp
- src/parsed_message.h
- src/search.h
- tests/dhtrunnertester.cpp
- tests/dhtrunnertester.h
Actually, packets are not retransmitted for listen operations. This
leads to some problems when they are already several values present
at one hash. Ideally, packets should be transmitted inside a request
to avoid packet loss and get all datas.
This patch breaks the compatibility with previous versions
> net: add updateValues to replace Listen operations

- include/opendht/dht_proxy_client.h
- src/dht_proxy_client.cpp
restartListeners() must be called only when the proxy is connected. Else, the
client will receive a lot of http errors
> proxyclient: only restart listeners when connected

- CMakeLists.txt
This enables Guix and NixOS to run tests in our builder's sandbox.
> Enable to disable network tests

- tools/CMakeLists.txt
For some reason 1778f640482aff728a35cc1f1591e010e1558524 (PR #524 from @atraczyk) reverted part of 4d70c214b0b69deb0ca4bffbf3056131b013378d (PR #510 from @doronbehar).
The commit from this PR fixes that.
> Fix use of OPENDHT_SYSTEMD_UNIT_FILE_LOCATION

- python/opendht.pyx
- python/opendht_cpp.pxd
Hi!
I just noticed that there are no python bindings for `TypeValue`. I'd really love to get all the Python bindings completed, but I'm quite short of time (and also I only needed `TypeValue` so I could set the expiration timer for my `Value`s, since it seems that there's no way to do this with the current state of the Python bindings).
I didn't add any tests for this nor did I run the benchmarks. The bindings for TypeValue work just fine, though. It's pretty much the same as in C++:
`node.registerType(dht.ValueType(1, "Name", datetime.timedelta(seconds=30)))`
Probably there are a few things here and there but for the most part it gets the job done.
Signed-off-by: JUAN MÉNDEZ <vpsink@gmail.com>
> Add python bindings for TypeValue

- tests/threadpooltester.cpp
While building on Arch, we had:
```
/build/opendht/src/opendht-2.3.1/tests/threadpooltester.cpp: In member function ‘void test::ThreadPoolTester::testThreadPool()’:
/build/opendht/src/opendht-2.3.1/tests/threadpooltester.cpp:47:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
47 |         std::this_thread::sleep_for(std::chrono::milliseconds(10));
|                           ^~~~~~~~~
/build/opendht/src/opendht-2.3.1/tests/threadpooltester.cpp: In member function ‘void test::ThreadPoolTester::testExecutor()’:
/build/opendht/src/opendht-2.3.1/tests/threadpooltester.cpp:76:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
76 |         std::this_thread::sleep_for(std::chrono::milliseconds(10));
|                           ^~~~~~~~~
```
> tests: fix building with GCC11

- CMakeLists.txt
- cmake/CheckAtomic.cmake
Currently this project cannot be compiled for `risc-v` architecture, `gcc` compiler raises an error:
```
/usr/bin/ld: libopendht.so.2.3.5: undefined reference to `__atomic_exchange_1'
```
This is because the `risc-v` architecture does not support 1-byte and 2-byte lock-free atomic operations.
By passing the `-latomic` option, `gcc` will statically link the `libatomic` library. Inside that library, the `std::atomic<bool>` used in the project will fallback to the mutex implementation, which is allowed by C++ standard.
Ref: https://github.com/riscv-collab/riscv-gnu-toolchain/issues/183#issuecomment-253721765
> Support `risc-v` architecture

- CMakeLists.txt
- cmake/CheckAtomic.cmake
- cmake/DetermineGCCCompatible.cmake
Context: #598
This PR contains changes:
- Updates `CheckAtomic.cmake` to the latest.
- Includes `DetermineGCCCompatible.cmake` to set `LLVM_COMPILER_IS_GCC_COMPATIBLE` variable correctly.
- Links to `libatomic` for all targets `if (NOT HAVE_CXX_ATOMICS_WITHOUT_LIB)`.
Compilation passes on macOS and RISC-V arch.
> cmake: fix incorrectly linking to libatomic on macOS

- src/value.cpp
Seen in Homebrew (https://github.com/Homebrew/homebrew-core/pull/101711) where we haven't added optional `jsoncpp` features
Issue was that `checkSignature` and `decrypt` were added inside the `#ifdef OPENDHT_JSONCPP`, so they weren't getting compiled resulting in
```
Undefined symbols for architecture x86_64:
"dht::Value::checkSignature()", referenced from:
dht::SecureDht::checkValue(std::__1::shared_ptr<dht::Value> const&) in securedht.cpp.o
std::__1::__function::__func<dht::SecureDht::secureType(dht::ValueType&&)::$_3, std::__1::allocator<dht::SecureDht::secureType(dht::ValueType&&)::$_3>, bool (dht::Hash<20ul>, std::__1::shared_ptr<dht::Value>&, dht::Hash<20ul> const&, dht::SockAddr const&)>::operator()(dht::Hash<20ul>&&, std::__1::shared_ptr<dht::Value>&, dht::Hash<20ul> const&, …
```
> value: fix build without jsoncpp

- include/opendht/dht_proxy_client.h
- include/opendht/dhtrunner.h
- src/dhtrunner.cpp
- src/network_engine.cpp
- src/value.cpp
If configured to run as a proxy client, no port will be bound and the local dht node
won't be instantiated.
Trying to use the proxy if not compiled will now trigger an exception.
> dhtrunner: remove support for running both dht and proxy client

- include/opendht/infohash.h
Current operator== creates a very weird warning about using an
uninitialized value (no warning without the reinterpret_cast).
> infohash: remove optimization due to weird warnings

- include/opendht/dht_proxy_client.h
- include/opendht/http.h
- src/dht_proxy_client.cpp
- src/http.cpp
When switching between two network interfaces, local address will
change but not the public ip. This generally cause the client to
not correctly updates its candidates.
In this patch, we inject in the proxy client the local candidates
and use it to check if the network changed.
> proxy_client: reconnect account if local ip changes

- src/dht_proxy_client.cpp
The current master is broken with clang, this fix the issue.
> dht_proxy_client: fix not contextually convertible to 'bool' error

- include/opendht/http.h
- src/http.cpp
In the previous version, the timeout for the connection could be
set only after async_connect while the request is sending.
This means if async_connect is slow (it can happen as if there is
an ipv6 endpoint, it can try to resolve it during dozens of seconds
before falling back on ipv4).
In this patch, it moves the timeout callback in the request. This
callback will be set just before async_connect, to be sure that we
are using the callback while connecting.
> http: modify timeout behaviour

- src/dht_proxy_server.cpp
when searching for a value to put, the proxy server returned a json with value->id = 0, causing the client to not refreshing correctly the values later (when timeout-ing, the value to refresh is not found).
> proxyserver: send correct value id to client

- include/opendht/dht_proxy_server.h
- src/dht_proxy_server.cpp
- tools/dhtnode.cpp
- tools/tools_common.h
Make the proxy able to support the UnifiedPush platform, so that applications using the proxy server can use any UnifiedPush provider.
Documentation: https://unifiedpush.org/
How to test:
+ Install a UnifiedPush provider on a device (e.g. https://ntfy.sh)
+ Run dhtnode with a proxyserver and --unifiedpush https://ntfy.sh
+ Subscribe to a random topic on ntfy (e.g. "dhtproxytest")
+ Subscribe to a hash on the DHT: curl -X SUBSCRIBE http://my.dht.proxy:8000/key/foo \ -d '{"key":"dhtproxytest", "platform":"unifiedpush"}'
+ Send data on the subscribed hash
Note: the topic should be completely random.
> proxyserver: add support for UnifiedPush standard

- include/opendht/dht_proxy_server.h
- src/dht_proxy_server.cpp
- tools/dhtnode.cpp
- tools/tools_common.h
Because there is multiple unifiedpush endpoint (ntfy.sh is one), we should not pass it as an option to dhtnode, but use the one provided by the user in the token (from unified push library).
> unifiedpush: remove unifiedpush parameter

- tools/dhtnode.cpp
dhtnode doesn't recognize "openpush" option.
> dhtnode.cpp: fix void print_usage()

- include/opendht/http.h
- src/http.cpp
For routes such as /api/auth/directory/search, when searching for names such as "Léo", jams would not respond to the request
since the URL contained invalid characters defined in RFC3986. `url_encode` turns such characters into their equivalent escaped characters.
> url_encode: escape url query

- doc/dhtnode.1
This fixes the following lintian issue:
```
22: warning: macro 'mF' not defined [usr/share/man/man1/dhtnode.1.gz:1]
```
> doc: fix dhtnode(1) man page formatting

- CMakeLists.txt
Link against libatomic also on architectures that need it for 64-bit atomic operations.  ARM EABI (armel) and little-endian MIPS (mipsel) are two such architectures.
> build/cmake: Link libatomic where needed for 64-bit atomic ops.

- include/opendht/dht_proxy_server.h
- src/dht_proxy_server.cpp
Avoids issues compiling with MSC.
Also move PushSessionContext definition outside the OPENDHT_PUSH_NOTIFICATIONS condition.
> dht_proxy_server: use lambda instead of std::bind for listen callback

- src/crypto.cpp
Add verifications to gnutls calls and throw expcetion with readable messages.
For example, if call loadIdentity and crt file has name different of private key exception message was
Can't get certificate public key ID: ASN1 parser: Value was not found.
However, the real problem is that crt file was not found. Now, for the same problem the exception message will be: Error while reading file.
> make crypto error messages more readable

- tests/dhtrunnertester.cpp
This change eliminates the following compiler warning without reducing readability:
```
/home/noviv/opendht/tests/dhtrunnertester.cpp: In lambda function: /home/noviv/opendht/tests/dhtrunnertester.cpp:292:89: warning: unused parameter ‘expired’ [-Wunused-parameter]
292 |     node2.listen(key2, [&](const std::vector<std::shared_ptr<dht::Value>>& values, bool expired){
|                                                                                    ~~~~~^~~~~~~
```
> Fix an unused parameter warning in dhtrunnertester

- src/crypto.cpp
- tests/cryptotester.cpp
- tests/cryptotester.h
Multiple compiler warnings note that the `gcm_aes_*` family of functions are deprecated. They have been replaced with `gcm_aes<key_length>_*`. This change uses the correct set of functions based on the given key size. Resolves #571.
Sample compiler warning:
```
/home/noviv/opendht/src/crypto.cpp: In function ‘dht::Blob dht::crypto::aesEncrypt(const uint8_t*, size_t, const dht::Blob&)’: /home/noviv/opendht/src/crypto.cpp:97:20: warning: ‘void nettle_gcm_aes_set_key(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
97 |     gcm_aes_set_key(&aes, key.size(), key.data());
|                    ^
In file included from /home/noviv/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:276:1: note: declared here
276 | gcm_aes_set_key(struct gcm_aes_ctx *ctx,
| …
```
> Get off of deprecated GCM AES methods

- include/opendht/peer_discovery.h
- src/dhtrunner.cpp
- src/peer_discovery.cpp
Add a timer to schedule `connectivityChanged` with a maximum interval of one minute. If `connectivityChanged` is called and the node status remains unchanged (still disconnected), it will be called three more times at intervals of 10s, 20s, and 40s. If the status changes during this process, the timer will be canceled.
> peer discovery: add a timer to schedule `connectivityChanged` 

- src/dht_proxy_server.cpp
This commit updates the format of the push notification requests sent by the DHT proxy server to conform to FCM's HTTP v1 API. (The previously used API was deprecated in 2023, see:
https://firebase.google.com/docs/cloud-messaging/migrate-v1) The "priority" and "ttl" (time to live) options are specific to Android and therefore need to be put in the "android" block, as documented here: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
> dht_proxy_server: fix Android push notifications

- src/value.cpp
All encrypted values put on the DHT currently have the default priority of 0 because the priority information is ignored by the Value::encrypt function.
> value: preserve priority when encrypting

- src/network_engine.cpp
Fix calls to DeserializeNodes. They must
catch possible exceptions
> Catch exception of DeserializeNodes

- .gitignore
- Addresses review: https://github.com/savoirfairelinux/opendht/pull/750#discussion_r2089277264 in #750 by @aberaud 
- Allows clean clone and build in MS Visual Studio with different settings
> MS Visual Studio .gitignore fix for CMake implicit builds

- CMakeLists.txt
- src/crypto.cpp
- Added GnuTLS version handler directives for versions 3.8.7 and later
https://github.com/savoirfairelinux/opendht/pull/750#discussion_r2089284896
- Removed `GNUTLS_INTERNAL_BUILD` definition to avoid problems with `gnutls_free()`
function (https://github.com/savoirfairelinux/opendht/pull/750#issuecomment-2832005765)
https://github.com/ShiftMediaProject/gnutls/blob/f78e2e673e84601283fb5ec353bfdd53204becd2/SMP/gnutls/gnutls.h#L2286
> Gnutls version handler

- include/opendht/default_types.h
Removes `OPENDHT_PUBLIC` specifier from templatized classes to avoid confusion of the MSVC compiler during Windows builds.
> Removed OPENDHT_PUBLIC specifier from templatized classes

- .github/workflows/windows-build.yml
Fix for [https://github.com/savoirfairelinux/opendht/security/code-scanning/7](https://github.com/savoirfairelinux/opendht/security/code-scanning/7)
To fix the problem, add an explicit `permissions` block to the workflow to restrict the GITHUB_TOKEN permissions to the minimum required. The best way to do this is to add a `permissions` block at the root level of the workflow (just after the `name:` and before `on:`), which will apply to all jobs unless overridden. For this workflow, the minimal required permission is `contents: read`, which allows jobs to read repository contents but not write to them. No additional imports or definitions are needed; this is a YAML configuration change.
> Fix for code scanning alert no. 7: Workflow does not contain permissions
