- python/tools/benchmark.py
I've refactored benchmark.py code. This will give benchmark.py *extensibility* so people can provide other tests easily.
> Benchmark refactoring 

- src/dhtrunner.cpp
Refs : https://msdn.microsoft.com/en-us/library/windows/desktop/ms740126%28v=vs.85%29.aspx
> Correctly close socket on win32

- include/opendht/dht.h
- include/opendht/dhtrunner.h
- include/opendht/value.h
- python/opendht.pyx
- python/opendht_cpp.pxd
- python/setup.py.in
- python/tools/benchmark.py
- python/tools/dhtnetwork.py
- src/dht.cpp
- src/dhtrunner.cpp
- src/value.cpp
Since the integration of the feature, removing periodic reannouncing of values has led to decrease of performance. I don't know the origin of the problem, but this PR provides a fix. This brings reannouncing values behavior back, but stops upon value expiration. I've also added my name and mail address to the project where relevant.
> performance fix to data persistence feature

- src/dht.cpp
> Simplify the simplification

- .gitignore
- CMakeLists.txt
- Makefile.am
- configure.ac
Ensure the library is built with thread support
Bump Mgspack required version to reflect use of 1.2 features.
> Minor cmake fixes

- python/tools/benchmark.py
- python/tools/dht/tests.py
Some minor code cleanups. I've also introduced the use of decorators for handling tasks executing before each tests.
> Benchmark python test cleanup

- python/tools/benchmark.py
- python/tools/dht/network.py
- python/tools/dht/tests.py
- python/tools/dht/virtual_network_builder.py
I have written a test giving a footprint of the traffic generated by the data persistence feature. My changes will also let any test written in the future to measure the associated traffic.
> [Benchmark] traffic test

- include/opendht/dht.h
- src/dht.cpp
This is a rebase of an old and closed PR (#30). It was planned to be part of another PR, but on a second thought, it wouldn't be clear enough. So I'm reopenning the PR.
@aberaud: can you review this?
> Search progressive refill optimisation

- python/CMakeLists.txt
- python/Makefile.am
- python/setup.py.in
This is addressing the matters discussed in #72.
> [packaging] support python installation with make DESTDIR=$DIR

- src/dht.cpp
Since the PR #97 going to add a new feature in the API i've tested it and saw that we can put / store a outdate data.
This PR fix this issue
> Fix outdated store of value

- include/opendht/dhtrunner.h
- src/dhtrunner.cpp
Since i need this feature (see #91) for the issue #61, here is the modification that correct #91.
> Add timepoint into the API of SecureDht and DhtRunner

- include/opendht/network_engine.h
- include/opendht/node_cache.h
- src/dht.cpp
- src/network_engine.cpp
- src/node_cache.cpp
Since I open issue #96 I also give this patch to merge.
Now the bootstrap is not done by using the cache instead of the closest bucket (and if needed bucket next to this closest bucket ).
> [PHT] Optimize search

- include/opendht/dhtrunner.h
- include/opendht/indexation/pht.h
- src/dht.cpp
- src/dhtrunner.cpp
- src/indexation/pht.cpp
This PR is finally the last update on #61.
I've tested it with benchmark and it works, could test it too with 2 dhtnode and work like a charm :D 
(Sadly this only add 300 lines for lots of time consumed by error and little fix in API and what so ever .)
> [PHT] Complete node splitting

- python/tools/benchmark.py
- python/tools/dht/network.py
- python/tools/dht/tests.py
I've upgraded the benchmark IPC to use [msgpack](https://github.com/msgpack/msgpack-python). All requests to sub networks now have atomic property to ensure the consistency in messages. I've also made some general refactoring.
> [benchmark] new ipc

- src/dht.cpp
This PR is completing some work unintentionaly left undone after the queries. This has left place to some bugs like infinite loops when one or more concurent queries would be issued before a first request would complete.
**This PR introduces the following behavior**:
When multiple queries are queued for a same hash, the search will find the closest node to which send the first queued query. This process will repeat for each queries until all queries are sent to a sufficient number of nodes.
*Note that no more than `MAX_REQUESTED_SEARCH_NODES` nodes will be solicited. However, if 100 requests are queued for a same hash, there could be up to 100x`MAX_REQUESTED_SEARCH_NODES` requests sent at the same time since we only count the solicited nodes and not the requests. This will most of the …
> [dht] concurrent queries

- include/opendht/node.h
- include/opendht/value.h
- src/dht.cpp
- src/network_engine.cpp
- src/value.cpp
This is one more consistency fix around operation timings. This PR also fixes a sneaky bug that has appeared in the queries code.
> [dht] bug fixes, timing computation enhancements

- include/opendht/network_engine.h
- include/opendht/sockaddr.h
- include/opendht/value.h
- src/dht.cpp
- src/network_engine.cpp
- src/utils.cpp
- src/value.cpp
* add support to fragment values in smaller UDP packets
* NetworkEngine level changes
* backward compatible for small (<8KB) values
> network: transmit large values in multiple packets

- src/dht.cpp
Attempt closest search and nearby searches
until we are too far instead of trying every
search.
> dht: try inserting new nodes smarter

- CMakeLists.txt
This patch was written by Gianfranco Costamagna as part of:
- https://bugs.debian.org/843788
> Multi-Arch support

- MSVC/msgpack-msvc.patch
- MSVC/opendht_deps.sln
- MSVC/project_get_dependencies.bat
change to maintained repos for gnutls, gmp, iconv, msgpack, nettle, and zlib
> msvc: change contrib repo sources

- include/opendht/indexation/pht.h
- src/indexation/pht.cpp
Prefer a const reference instead of shared_ptr if the shared_ptr
is not used and argument type is not changed in the method.
This allows to prevent useless shared_ptr allocations.
In getRealPrefix, use OpState to track state instead of using many
different shared_ptr.
> pht: prevent unneeded use of shared_ptr

- MSVC/opendht.vcxproj
- MSVC/opendht.vcxproj.filters
Added the recently created files to the VS project along with filters for source and header files
> add listener.h, search.h, and storage.h to VS project

- include/opendht/dht_interface.h
- include/opendht/securedht.h
Make DHT_LOG static to use it in the whole library.
Fix #230
> dht_interface: fix logger issues

- .travis.yml
- docker/DockerfileDepsProxy
- docker/DockerfileLlvm
- docker/DockerfileTravis
- docker/DockerfileTravisLlvm
- docker/DockerfileTravisProxy
- include/opendht/dht_proxy_client.h
- include/opendht/dht_proxy_server.h
- include/opendht/securedht.h
- src/dht_proxy_client.cpp
- src/dhtrunner.cpp
- tools/dhtnode.cpp
fix #242.
By the way, I worked a little on the travis script to avoid this kind of issue next time by testing builds with different parameters in parallel.
> pushnotifications: fix build without push notifications, improve travis script

- include/opendht/dht_proxy_client.h
- src/dht_proxy_client.cpp
- tools/dhtnode.cpp
Fill the body of the UNSUBSCRIBE method and fix dhtnode application
Should fix #244
> dhtproxy: fix cancelListen with pushNotifications

- src/dht_proxy_server.cpp
> proxyserver: fix cancelListen and reduce push notifications number

- include/opendht/dht_proxy_client.h
- src/dht_proxy_client.cpp
> proxyclient: avoid useless opFailed when correctly cancel a listen

- src/dht.cpp
- src/dht_proxy_client.cpp
- src/value.cpp
Note: Also fix Value deserialization
> dht_proxy_client: fix getCallback for push notifications

- include/opendht/dht_proxy_client.h
- src/dht_proxy_client.cpp
Factor various ways of sending listen requests.
> proxy client: refactor

- CMakeLists.txt
- tests/Makefile.am
- tests/dhtproxytester.cpp
- tests/dhtproxytester.h
Like dhtrunnertester add testGetPut for the dht_proxy_server.
> tests: begin tests for dht_proxy_server

- src/dhtrunner.cpp
The token used to cancel a listener was wrong. Indeed, tokenBGlobal
was used to get the linked listener, not to identify the listener
inside dhtrunner.
> dhtrunner: don't use listeners structure without proxy client enabled

- include/opendht/callbacks.h
- include/opendht/dht_proxy_server.h
- src/callbacks.cpp
- src/dht_proxy_server.cpp
- tools/dhtnode.cpp
Just to be compatible with my monitor app :)
> proxyserver: add stats endpoint for monitoring

- src/dht_proxy_client.cpp
callback_.emplace_back() returns immediately, so, in some case,
finished can be set to true even before we execute one callback.
Finished should be set to true only when donecb is executed or
if a callback returns false.
This improve the reactivity of the proxy client.
> dht_proxy_client: fix finished behavior

- src/network_engine.cpp
> A obviouse bug on network engine

- src/dht.cpp
When a permanent put is refreshed, the node has to tell to its
remote listeners that the value is refreshed.
> dht: link to tellListenerRefreshed

- src/peer_discovery.cpp
Test to let windows multicast be received by Linux
> Test: change ip multicast address to organization local

- src/dht_proxy_server.cpp
```
n0t testssl.sh $ ./testssl.sh -R 127.0.0.1:8080
###########################################################
testssl.sh       3.0rc5 from https://testssl.sh/dev/
(92654b2 2019-08-12 12:31:46 -- )
This program is free software. Distribution and
modification under GPLv2 permitted.
USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!
Please file bugs @ https://testssl.sh/bugs/
###########################################################
Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]
on lust:./bin/openssl.Linux.x86_64
(built: "Jan 18 17:12:17 2019", platform: "linux-x86_64")
Start 2019-08-18 13:18:01        -->> 127.0.0.1:8080 (127.0.0.1) <<--
rDNS (127.0.0.1):       10
Service detected:       HTTP
Testing for Renegotiation vulnerabilities 
Secure Renegotiation (RFC 5746) …
```
> dhtproxy: patch client renegotiation

- include/opendht/peer_discovery.h
- src/peer_discovery.cpp
- tests/peerdiscoverytester.cpp
- tests/peerdiscoverytester.h
https://git.jami.net/savoirfairelinux/ring-project/issues/662#
> peerdiscovery: refactor to camelcase & fix warning

- src/http.cpp
- tested with http://httpstat.us/400 etc
- client test sample: [http_errors.cpp](https://github.com/binarytrails/various/blob/master/cpp/opendht/http_errors.cpp
)
- test all 4xx 5xx codes with ```for code in $(seq 400 500); do ./http_errors.out $code; done```
> http: close connection if server requests

- src/http.cpp
Attempt to blind fix an isolated crash on Android (could not reproduce) due to a racing condition:
```
#00  pc 000000000058e954  /data/app/cx.ring-Vrpb3iaQayUczqQC0WsN4g==/lib/arm64/libring.so (dht::http::Connection::close()+20)
#01  pc 0000000000571364  /data/app/cx.ring-Vrpb3iaQayUczqQC0WsN4g==/lib/arm64/libring.so (dht::DhtProxyClient::restartListeners()+1452)
#02  pc 00000000005840b4  /data/app/cx.ring-Vrpb3iaQayUczqQC0WsN4g==/lib/arm64/libring.so (dht::DhtProxyClient::connectivityChanged()+24)
#03  pc 000000000054df28  /data/app/cx.ring-Vrpb3iaQayUczqQC0WsN4g==/lib/arm64/libring.so (dht::DhtRunner::loop_()+588)
```
> http: ensure safe connection destruction

- include/opendht/network_engine.h
- src/dht.cpp
- src/network_engine.cpp
This patch migrates tellListenerRefreshed and tellListenerExpired
to the new behavior
> listener: fully migrate to requests

- tools/dhtproxy_stats.py
> proxy: only keep last total stat

- cmake/CheckAtomic.cmake
> cmake: fix atomic check, hopefully

- include/opendht/crypto.h
- src/crypto.cpp
This allow to create certificate with a different validity than
10 years and be able to change the expiration of a certificate
> crypto: add parameter to change Certificate's validity period

- python/tools/README.md
- python/tools/dht/network.py
- python/tools/dht/virtual_network_builder.py
The current scripts use outdated API that is not working on latest pyroute2 version.
This PR will contain two commits reflecting two steps:
> python/tools: update network builder

- src/dht_proxy_server.cpp
When a second permanent put request was received, we didn't call async_wait after changing the expiration, causing push to not be sent the second day and presence to expire on some devices after ~3 days.
> dht_proxy_server: fix permanent put

- include/opendht/crypto.h
- src/crypto.cpp
> Add loadIdentity

- src/network_utils.cpp
select is limited to file descriptor numbers below FD_SETSIZE (1024), and calling FD_SET with a higher value can cause a buffer overflow. This can be problematic for applications using OpenDHT as a library.
> network_utils: use poll instead of select

- src/compat/getif_workaround_android.h
> getif_workaround_android.h: fix get_interface()

- include/opendht/indexation/pht.h
is too much node → are too many nodes
> pht.h: cleanup

- src/dht.cpp
Sentence case
can't → unable to
shuting → shutting
try → attempt
@aberaud
> dht.cpp: cleanup

- configure.ac
- src/compat/msvc/unistd.h
- tools/dhtcnode.c
* src/compat/msvc/unistd.h (usleep): Replace with...
(nanosleep): ... this.
* tools/dhtcnode.c (main) <usleep>: Replace with nanosleep.
Fixes: #607
> replace usleep with nanosleep

- configure.ac
A few small improvements to the configure.ac file made years ago when improving the opendht packaging for GNU Guix.
> Configure.ac improvements
